### ISSUE TITLE
java version

### ISSUE THREAD

**Issue by njuzh** [e32wong/clocom#3]
Hi, I want to reproduce your work but I ran into some problem when I tried to compile the project, so I hope you can tell me the correct java version that suit your work.
BTW, my java version is :
![image](https://user-images.githubusercontent.com/28818162/64317952-970d3480-cfeb-11e9-9fa7-d8d21ff8ea32.png)

**Comment by e32wong** [comment]
Please check out our README for the installation instruction. We only support openjdk-8-jdk and you are using Sun's Java.

**Comment by njuzh** [comment]
thanks! Does it apply to python programs?

**Comment by e32wong** [comment]
If you need to use the Python script to parse the Stack Overflow database then Python version 2.7 will work.

**Comment by njuzh** [comment]
Sorry, but I mean if I can use your tool to generate comment for Python programs?

**Comment by e32wong** [comment]
No. You will have to replace the tokenizer and the hashing functions if you want Python support. Since our code clone detection tool utilizes a scatter plot algorithm that expects hashed tokens as the input, it is relatively easy to replace it.

I do not expect Python to work as well compared to Java unless you have a Python parser that can inference the type of the variable. The reason is because you will get extremely poor clone detection results  due to the lack of static typing information.
